# Generated by Django 5.2.17 on 2026-09-14 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipwarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_links', to='inventory.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='uniq_membership_user_org'),
        ),
        migrations.AddConstraint(
            model_name='membershipwarehouse',
            constraint=models.UniqueConstraint(fields=('membership', 'warehouse'), name='uniq_membership_warehouse'),
        ),
    ]
