# Generated by Django 5.2.17 on 2026-09-14 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(default='BJ', max_length=2)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField(default=0)),
                ('timezone', models.CharField(default='Africa/Porto-Novo', max_length=64)),
                ('language', models.CharField(default='fr', max_length=8)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=32)),
                ('tax_enabled', models.BooleanField(default=False)),
                ('tax_rate_bps', models.PositiveIntegerField(default=0, help_text='Taux en points de base. 1800 = 18%.')),
                ('prices_include_tax', models.BooleanField(default=True)),
                ('max_discount_percent_manager', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='TRIAL', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'kind'), name='uniq_org_document_kind')],
            },
        ),
    ]
