# Generated by Django 5.2.17 on 2026-10-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_subscription_custom_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='SUSPENDED', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(choices=[('TRIAL', 'Essai Gratuit 14j'), ('MONTHLY', 'Mensuel (5 000 F)'), ('QUARTERLY', 'Trimestriel (12 500 F)'), ('CUSTOM', 'Déploiement Sur-Mesure')], default='MONTHLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformsubscriptionconfig',
            name='trial_days',
            field=models.PositiveSmallIntegerField(default=0, help_text="Durée de la période d'essai gratuit en jours (0 = désactivé)."),
        ),
    ]
