# Generated by Django 5.2.17 on 2026-10-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_trial_7_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='plan',
            field=models.CharField(choices=[('TRIAL', 'Essai Gratuit 7j'), ('MONTHLY', 'Mensuel (5 000 F)'), ('QUARTERLY', 'Trimestriel (12 500 F)'), ('CUSTOM', 'Déploiement Sur-Mesure')], max_length=20),
        ),
    ]
